Modularize and fix script

diff --git a/scripts/check-json b/scripts/check-json
--- a/scripts/check-json
+++ b/scripts/check-json
@@ -1,20 +1,29 @@
 #!/bin/bash
 
-result=$(find tests -type f -name "*.json" | xargs grep 'paraview do output' | grep "true" | cut -d':' -f1)
-result=$(find tests -type f -name "*.json" | xargs grep -F '"verbosity level"' | grep "1|2|3|4|5" | cut -d':' -f1)
-result=$(find tests -type f -name "*.json" | xargs grep -F '"output verbosity"' | grep "1|2|3" | cut -d':' -f1)
+test()
+  {
+    result=$(find tests -type f -name "*.json" | xargs grep "$1" | grep -E "$2" | cut -d':' -f1)
 
-[ -z "$result" ] && return 0
+    [ -z "$result" ] && return 0
 
-echo $result
-echo "Error in test .json-files: output is enabled in following files:"
+    echo "Error in test .json-files: $3:"
 
-sorted=($(sort <<<"${result[*]}"));
+    sorted=($(sort <<<"${result[*]}"));
 
-for i in "${sorted[@]}"
-do
-   echo "  $i"
-done
+    for i in "${sorted[@]}"
+    do
+       echo "  $i"
+    done
 
-return 1
+    return 1
+  }
+
+# test 1: "paraview" -> "paraview do output"
+test '\"paraview do output\"' 'true' 'output is enabled in following files' || return 1
+
+# test 2: "base" -> "verbosity level"
+test '\"verbosity level\"' '\"1\"|\"2\"|\"3\"|\"4\"|\"5\"' 'verbosity level is not correct in following files' || return 1
+
+# test 3: "Navier-Stokes" -> "Output options" -> "output verbosity"
+test '\"output verbosity\"' '\"1\"|\"2\"|\"3\"' 'output verbosity is not correct in following files' || return 1
 
